[workspace]
authors = ["Chan Jian Le <jianle001@e.ntu.edu.sg>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "example_turtlebot_project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
sim = "ros2 run turtlesim turtlesim_node"

[dependencies]
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-turtlesim = ">=1.8.3,<2"
